<?php

namespace GotChosen\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GotChosen\SiteBundle\Entity\MassMailQueue;

/**
 * MassMailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MassMailQueueRepository extends EntityRepository
{
    /**
     * @return MassMailQueue[]
     */
    public function findNew()
    {
        return $this->findBy(['status' => MassMailQueue::STATUS_NEW], ['dateAdded' => 'ASC']);
    }

    /**
     * @return MassMailQueue[]
     */
    public function findReadyToProcess()
    {
        $qb = $this->createQueryBuilder('q');
        $qb->where($qb->expr()->in('q.status',
            [MassMailQueue::STATUS_NEW, MassMailQueue::STATUS_PROCESSING, MassMailQueue::STATUS_RESUMING]));
        $qb->orderBy('q.dateAdded', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
