<?php

namespace GotChosen\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsergMeshNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsergMeshNetworkRepository extends EntityRepository
{
}
