<?php

namespace GotChosen\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoStatusRepository extends EntityRepository
{
}
